#!/usr/bin/env npx tsx
/**
 * Bootstrap a new gym deployment.
 *
 * Usage:
 *   npx tsx scripts/bootstrap-gym.ts
 *
 * What it does:
 *   1. Prompts for gym details (name, city, address, email, timezone, etc.)
 *   2. Generates a .env.local file (or updates an existing one)
 *   3. Upserts gym identity into site_settings via Supabase
 *   4. Customizes the waiver template with the gym's legal details
 *   5. Prints a post-setup checklist
 *
 * Prerequisites:
 *   - Supabase project created and migrations applied
 *   - .env.local with at least SUPABASE_URL, ANON_KEY, and SERVICE_ROLE_KEY
 *
 * There is no payment processor to set up: the gym collects payment in person.
 */

import * as readline from "readline";
import * as fs from "fs";
import * as path from "path";
import { createClient } from "@supabase/supabase-js";

// ── Helpers ──────────────────────────────────────────────────────────────────

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string, defaultVal?: string): Promise<string> {
  const suffix = defaultVal ? ` [${defaultVal}]` : "";
  return new Promise((resolve) => {
    rl.question(`  ${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultVal || "");
    });
  });
}

function hr() { console.log("─".repeat(60)); }

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("");
  hr();
  console.log(" GYM PLATFORM — NEW GYM SETUP");
  hr();
  console.log("");

  // ── Step 1: Collect gym info ────────────────────────────────────────────

  console.log(" Step 1: Gym Identity\n");

  const gymName       = await ask("Gym name (legal/full)", "My Gym");
  const shortName     = await ask("Short name (2-3 words)", gymName.split(" ").slice(0, 2).join(" "));
  const logoText      = await ask("Logo text (1-4 chars)", shortName.split(" ").map(w => w[0]).join("").toUpperCase());
  const cityName      = await ask("City name");
  const address       = await ask("Street address");
  const state         = await ask("State/Province");
  const zip           = await ask("Postal code");
  const phone         = await ask("Phone number");
  const email         = await ask("Contact email");
  const timezone      = await ask("IANA timezone", "America/Chicago");
  const siteUrl       = await ask("Site URL", "http://localhost:3000");
  const instagramUrl  = await ask("Instagram URL (blank to skip)");
  const instagramHandle = instagramUrl ? await ask("Instagram handle", "@" + gymName.replace(/\s+/g, "")) : "";
  const affiliateText = await ask("Footer tagline (1 sentence about the gym)", `${gymName}. Training athletes of all levels.`);
  const metaTitle     = await ask("SEO title", `${gymName} | ${cityName}`);
  const metaDesc      = await ask("SEO description", `Train at ${gymName} in ${cityName}. Classes for all levels.`);
  const legalEntity   = await ask("Legal entity name (for waiver)", gymName);
  const legalState    = await ask("Legal jurisdiction state", state);

  console.log("");
  hr();
  console.log(" Step 2: Environment Variables\n");

  // Check if .env.local exists
  const envPath = path.resolve(process.cwd(), ".env.local");
  const envExamplePath = path.resolve(process.cwd(), ".env.local.example");

  let supabaseUrl = "";
  let supabaseAnonKey = "";
  let supabaseServiceKey = "";

  if (fs.existsSync(envPath)) {
    console.log("  Found existing .env.local — reading Supabase credentials...\n");
    const envContent = fs.readFileSync(envPath, "utf8");
    supabaseUrl = envContent.match(/NEXT_PUBLIC_SUPABASE_URL=(.+)/)?.[1]?.trim() || "";
    supabaseAnonKey = envContent.match(/NEXT_PUBLIC_SUPABASE_ANON_KEY=(.+)/)?.[1]?.trim() || "";
    supabaseServiceKey = envContent.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)?.[1]?.trim() || "";
  }

  if (!supabaseUrl) supabaseUrl = await ask("Supabase URL");
  if (!supabaseAnonKey) supabaseAnonKey = await ask("Supabase anon key");
  if (!supabaseServiceKey) supabaseServiceKey = await ask("Supabase service role key");

  const superAdminPw = await ask("Super Admin password (min 16 chars)", "");

  // Write .env.local
  const envContent = `# ─────────────────────────────────────────────────────────────────
# ${gymName} — Environment Variables
# Generated by bootstrap-gym.ts on ${new Date().toISOString().split("T")[0]}
# ─────────────────────────────────────────────────────────────────

# Supabase
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}

# Site
NEXT_PUBLIC_SITE_URL=${siteUrl}
${superAdminPw ? `\n# Super Admin\nSUPER_ADMIN_PASSWORD=${superAdminPw}` : "# SUPER_ADMIN_PASSWORD= (set a strong password to enable /super-admin)"}
`;

  fs.writeFileSync(envPath, envContent);
  console.log(`  ✓ Wrote ${envPath}\n`);

  // ── Step 3: Seed site_settings ──────────────────────────────────────────

  console.log("");
  hr();
  console.log(" Step 3: Seeding Database\n");

  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  const settings: [string, string][] = [
    ["gym_name", gymName],
    ["gym_short_name", shortName],
    ["gym_logo_text", logoText],
    ["gym_logo_dot", "\u2022"],
    ["gym_city_name", cityName],
    ["gym_tagline", "Train. Improve. Belong."],
    ["gym_timezone", timezone],
    ["gym_affiliate_text", affiliateText],
    ["gym_footer_tags", ""],
    ["gym_join_button_text", `Join ${shortName}`],
    ["gym_meta_title", metaTitle],
    ["gym_meta_description", metaDesc],
    ["gym_meta_url", siteUrl],
    ["gym_instagram_url", instagramUrl],
    ["gym_instagram_handle", instagramHandle],
    ["contact_address", address],
    ["contact_city", cityName],
    ["contact_state", state],
    ["contact_zip", zip],
    ["contact_phone", phone],
    ["contact_email", email],
  ];

  let settingsOk = true;
  for (const [key, value] of settings) {
    if (!value) continue;
    const { error } = await supabase
      .from("site_settings")
      .upsert({ key, value }, { onConflict: "key" });
    if (error) {
      console.error(`  ✗ Failed to set ${key}: ${error.message}`);
      settingsOk = false;
    }
  }
  if (settingsOk) console.log(`  ✓ Seeded ${settings.filter(([, v]) => v).length} site_settings rows`);

  // ── Step 4: Customize waiver ────────────────────────────────────────────

  const fullAddress = `${address}, ${cityName}, ${state} ${zip}`;

  const { data: activeWaiver } = await supabase
    .from("waiver_templates")
    .select("id, body_md, title")
    .eq("active", true)
    .single();

  if (activeWaiver) {
    const customBody = activeWaiver.body_md
      .replace(/\[GYM NAME\]/g, legalEntity)
      .replace(/\[GYM ADDRESS\]/g, fullAddress)
      .replace(/\[GYM EMAIL\]/g, email);

    const customTitle = `${legalEntity} — Membership & Liability Waiver`;

    // Check if waiver still has placeholders (hasn't been manually edited)
    const hasPlaceholders = activeWaiver.body_md.includes("[GYM NAME]");

    if (hasPlaceholders) {
      const { error } = await supabase
        .from("waiver_templates")
        .update({ title: customTitle, body_md: customBody })
        .eq("id", activeWaiver.id);

      if (error) {
        console.error(`  ✗ Failed to customize waiver: ${error.message}`);
      } else {
        console.log("  ✓ Customized waiver template with gym details");
      }
    } else {
      console.log("  ⊘ Waiver already customized — skipped");
    }

    // Add severability state
    if (legalState) {
      const { data: current } = await supabase
        .from("waiver_templates")
        .select("body_md")
        .eq("id", activeWaiver.id)
        .single();
      if (current?.body_md.includes("applicable law")) {
        const updated = current.body_md.replace(
          "applicable law",
          `the laws of the **State of ${legalState}**`
        );
        await supabase
          .from("waiver_templates")
          .update({ body_md: updated })
          .eq("id", activeWaiver.id);
        console.log(`  ✓ Set waiver jurisdiction to State of ${legalState}`);
      }
    }
  } else {
    console.log("  ⚠ No active waiver template found — create one in Admin → Waivers");
  }

  // ── Done ────────────────────────────────────────────────────────────────

  console.log("");
  hr();
  console.log(" SETUP COMPLETE");
  hr();
  console.log("");
  console.log(" Post-setup checklist:");
  console.log("");
  console.log("  □ Run 'npm run dev' and verify the site loads");
  console.log("  □ Log into /admin and review the waiver (Admin → Waivers)");
  console.log("  □ Set your kiosk PIN (Admin → Settings)");
  console.log("  □ Upload a hero image (Admin → Hero)");
  console.log("  □ Add team members (Admin → Team)");
  console.log("  □ Create membership plans (Admin → Membership Plans)");
  console.log("  □ Set up your schedule (Admin → Schedule)");
  console.log("  □ Configure the theme (Admin → Appearance)");
  console.log("  □ Set hours & map embed (Admin → Location)");
  console.log("  □ Visit /super-admin to verify platform access");
  console.log("  □ Create an admin user:");
  console.log("    1. Sign up at /join");
  console.log("    2. In Supabase SQL editor: UPDATE profiles SET is_admin = true WHERE email = 'your@email.com';");
  console.log("");

  rl.close();
}

main().catch((err) => {
  console.error("\n  Error:", err.message);
  process.exit(1);
});
