-- Add starts_at to all entities that have expires_at
ALTER TABLE banners ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE updates ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE pricing_plans ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE faq_items ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ DEFAULT NULL;

-- Schedule gets expires_at, starts_at, and badge
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS badge TEXT DEFAULT NULL;

-- Blog posts get both dates
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ DEFAULT NULL;
